### ISSUE TITLE
examples for attract emitter

### ISSUE THREAD

**Issue by myoung34** [meduzapat/LEDSpicer#12]
Long time no see

Im updating and trying to move from pulseaudio to the attract emitter

I get this error from ledspicer (latest running on arch linux):

```
[barcaderator@barcaderator barcaderator config backup]$ emitter LoadProfileByEmulator digdug arcade
sed: can't read /usr/local/share/ledspicer/controls.ini: No such file or directory
sed: can't read /usr/local/share/ledspicer/colors.ini: No such file or directory
```

I dont see anywhere on how these files should look (colors.ini and controls.ini)

my profile xml: 

```
$ sudo cat /usr/local/share/ledspicer/profiles/profile_arcade.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!-- profile skeleton -->
<LEDSpicer
	version="1.0"
	type="Profile"
	backgroundColor=""
>
	<!-- Sample start transition -->
	<startTransition
		type="Pulse"
		color="Red"
		speed="Fast"
		filter="Combine"
		direction="ForwardBouncing"
	/>
	<!-- Sample end transition -->
	<endTransition
		type="Pulse"
		color="Red"
		speed="Fast"
		filter="Combine"
		direction="ForwardBouncing"
	/>
</LEDSpicer>
```

```
$ sudo cat /usr/local/etc/ledspicer.conf
<?xml version="1.0" encoding="UTF-8"?>
<LEDSpicer
    logLevel="Error"
    port="16161"
    version="1.0"
    type="Configuration"
    fps="30"
    userId="1000"
    groupId="1000"
    colors="basicColors" 
    craftProfile="true"
    colorsFile="true"
    dataSource="controls.ini,file"
>
    <devices>
        <device
            name="UltimarcPacLed64"
            boardId="1"
        >
...snipped...
```

**Comment by myoung34** [comment]
If i remove `colorsFile` and `dataSource` from ledspicer.conf I get:

```
[barcaderator@barcaderator barcaderator config backup]$ /usr/local/bin/ledspicerd -f
Program terminated by error: Unable to read the file /usr/local/share/ledspicer/animations/.xml Error=XML_ERROR_FILE_NOT_FOUND ErrorID=3 (0x3) Line number=0: filename=/usr/local/share/ledspicer/animations/.xml
```

**Comment by meduzapat** [comment]
hey What is up? long time, remember we still have the slack chat, you need that too files or remove the config, I did several changes on the last version that are not compatible anymore with the old config but they fixes, and bring a lot of features!!
now the profiles can be read from 3 places (mame, a color.ini file and trhe old xml file)
the ini files changes a bit, instead of having the settings into the profile, I moved them into an input config, is just cut paste.
check this section: https://sourceforge.net/p/ledspicer/wiki/Input%20Plugins/

**Comment by myoung34** [comment]
I think my configs are fine. highlighting games in attract flashes red but I dont see how it knows about game specific colors.

For example if i highlight digdug or launch it the buttons stay dark

**Comment by myoung34** [comment]
![](https://im2.ezgif.com/tmp/ezgif-2-108d343ce3.gif)

**Comment by meduzapat** [comment]
https://howlerskunkworks.slack.com/archives/CUSURKNEP

**Comment by myoung34** [comment]
I dont have an account on that slack so it wont let me see it

**Comment by meduzapat** [comment]
you can use the web browser version, no need to install the program, this is your invite:
https://join.slack.com/t/howlerskunkworks/shared_invite/zt-11l54d8uf-WEeOqHX0HIScYS3ON9A6Yw
