### ISSUE TITLE
Audio popping  when switching restrictors

### ISSUE THREAD

**Issue by silverl** [meduzapat/LEDSpicer#13]
Hi, thanks for this AMAZING codebase! Just started using it this week.

I'm writing because I'm hearing audio popping on my Raspberry Pi 4b with speakers connected to the headphone jack whenever the restrictors on my Servostiks are switched.

It's always two pops in rapid succession. The best description is that it sounds like someone pulling the audio cable out of the computer when the speakers are powered up.

Before I figured out how to control restrictors with LEDSpicer, I was switching the servos using https://github.com/mahuti/setservostik   setservostik does not cause the same audio artifacts.

I thought you might want to know or have an idea what might be causing it.

Commenting out the restrictors XML element makes the sound stop. Putting them back in brings back the sound artifact.

Thanks!

**Comment by silverl** [comment]
I forgot to mention I also have an UltraStik 360 in my build. I get the popping noise even when only the UltraStick is in the list of restrictors. This would seem to indicate whatever is making the noise is independent of the physical servo mechanisms that are used for the ServoStiks. My UltraStick does not have a physical restrictor plate attached, so the "restricting" should only be happening in software.

**Comment by silverl** [comment]
Just last night I was working on the cab and put the rotators element back in place, and there was no more popping. 

I don't know what the deal is. Only that it apparently stopped. I've been making a lot of changes to configuration, and maybe I changed some setting that impacted this.

We're not going to get a clean repro at this point.

So I'm going to say "thank you" for jumping in here, and I'm sorry I spun you up. I'll close this out and if it starts happening again, I'll reopen.

**Comment by meduzapat** [comment]
Good to know, anyway let me know if the issue raise again or if you need help, I will try to update the document this weekend
