### ISSUE TITLE
Installing on Recalbox 

### ISSUE THREAD

**Issue by mattjonesc** [meduzapat/LEDSpicer#15]
Hello,
First of all, thank you for creating this package. 

background: I have a pi 4b setup with an Ultimarc Ultimate Ipac board. I’ve been trying the get a package that I can install with Recalbox. I’m unable to do a compile and install on my Recalbox build as it’s a buildroot os. I was hoping to compile on a separate build and then copy over the necessary files and executeables.  I was able to achieve this following the link here for Katie Snows umtool:

https://gitlab.com/recalbox/recalbox/-/issues/2265

However this only allows me to do very limited commands with the leds. 

My question is, if I compile and install as outlined in your docs, what resulting files would I need to migrate to Recalbox in order for ledspicer to run?

apologies if this is trivial but I’m still learning Linux as a result of building my arcade cabinet.

thanks!

**Comment by meduzapat** [comment]
Hey there, looks like you actually get it working fine, when you say "However this only allows me to do very limited commands with the leds." that means that you got it working.
I have almost done with the 1st part of the LEDSpicer UI to help with the configuration part that is the most complex!

You can join [our Slack channel](https://join.slack.com/t/howlerskunkworks/shared_invite/zt-1vlzkhy12-IcI7D1k5JXcPEIbsYHl6xA) to ask for help on the setup

**Comment by mattjonesc** [comment]
Looks like I'm on the right path!  Thank you!  I will try out the slack channel.  Much appreciated.
