### ISSUE TITLE
Support for multiple Ultimarc I-PAC Ultimate boards?

### ISSUE THREAD

**Issue by nicholas-ochoa** [meduzapat/LEDSpicer#17]
I have two I-PAC Ultimate boards, one is flashed with the "ID #2" firmware provided by Ultimarc to run a dual board set up. When I look at the Vendor / Product ID for my boards, I see one of them is d209:0410 (which is expected), and the other board (which is flashed as "ID #2") shows up as d209:0411. 

Is there any way this can be supported? 

<img width="751" alt="image" src="https://github.com/meduzapat/LEDSpicer/assets/126299/18a7c1aa-c238-45f5-96e1-4ade0f181e50">
<img width="758" alt="image" src="https://github.com/meduzapat/LEDSpicer/assets/126299/e6114f69-9d4a-4c62-8836-5246e6c05e60">

**Comment by meduzapat** [comment]
hey, they should work, I have 1 IPAC Ultimate and 1 PAC64 working together. let me know if not, when you set them, use the correct IDs :)
