### ISSUE TITLE
Slack Channel Still Available?

### ISSUE THREAD

**Issue by MizterB** [meduzapat/LEDSpicer#19]
I see several mentions of a Slack channel in this repo, but when I visit https://join.slack.com/t/howlerskunkworks/shared_invite/zt-11l54d8uf-WEeOqHX0HIScYS3ON9A6Yw, I get the message "This link is no longer active".  Is there still a space for collaboration?

**Comment by meduzapat** [comment]
Yes, I created a new link for you, they expire after a time
https://join.slack.com/t/howlerskunkworks/shared_invite/zt-22cex6601-iMffiKfej2P3Rvm9R8K4oQ
