### ISSUE TITLE
Ledspicer daemon + pacdrive messes up Attract Mode

### ISSUE THREAD

**Issue by substring** [meduzapat/LEDSpicer#2]
Hi,

It seems ledspicer is giving a hard time to AM. When ledspicer is started as a daemon, it prevents AM from starting. If the deamon is manually launched after AM has started, AM reaches 100% CPU and is sluggish.

This doesn't happen when ledspicerd is started as user.

The PC needs a full power fycle off ->on to work again normally, resetting doesn't fix anything.

Tested in Arch Linux/GroovyArcade.

**Comment by meduzapat** [comment]
I will check

**Comment by substring** [comment]
on your topic on BYOAC ?

**Comment by meduzapat** [comment]
version 0.4.2 fixes this issue
