### ISSUE TITLE
I hated to do this but couldn't figure out a way to contact someone that really knew what they were doing getting this going on Retropie 4.8

### ISSUE THREAD

**Issue by wtstreetglow** [meduzapat/LEDSpicer#24]
Hello,

Could you direct me to someone that could help me get this going on a retropie arcade install. 

I gave up on another software called RGB Commander because I never could get it going properly in terms of getting the arcade roms to update to the proper color/ number when playing an arcade rom, I also couldn't get it to work with regards to proper color/ number when choosing an individual console game (not rom specific, but controller specific).

I am running my games from a network share which I have setup with the pi using: sudo mount -t cifs -o username=WESTON,password=xxxx,nounix,noserverino //WESTONSPC/roms /home/pi/RetroPie/roms(not sure if that caused my issues with RGB Commander, but I don't think it did since it seems these led style programs are rom name/ emulator name (string) based with no basis on the files locations)

So now I am attempting to get LEDSpicer running (I believe it needs to run in conjunction with LEDSpicer Emitter Plugin but I don't really know that for sure either.)

I immediately start out confused on LEDSpicer with the wiki at https://sourceforge.net/p/ledspicer/wiki/Deployment/#building-ledspicer.
I'm seeing an easy way to install of a PPA? I don't really know what that is but it worries me that it hasn't been updated since 2020 and there are recent commits showing here. That makes me believe I shouldn't go that route. 
Could I have even used that being that I am wanting to use this with Retropie/ Emulations Station?

I apologize for all of the questions. I am going to attempt to get LEDSpicer going tonight using the information provided at the wiki and installing from source. I was really just hoping you could direct me to somewhere for a little support as I have a feeling I may end up needing it. (I have posted at the arcade controls forum and retropie forum but no one has really replied)

Thank you Patricio!

**Comment by meduzapat** [comment]
can you join this discord channel ?
[Discord LEDSpicer channel](https://discord.gg/xb6xhnam)
