### ISSUE TITLE
Random behavior with LED-WIZ on newer systems?

### ISSUE THREAD

**Issue by gray-space** [meduzapat/LEDSpicer#4]
Hi again,

I'm running into a new issue: when testing my control panel using ledspicerd -l. I get perfect behavior on older systems (my workbench system which is from 2006 or so, and a netbook from 2007). Tell it to turn on an output, and it turns it on, 

However. I have problems when running LEDSpicer newer hardware: an UDOO x86 single-board system (which only has USB3) a recent Intel mini-ITX motherboard (which, according to Linux, has a single USB3 controller), and a 2017 HP laptrop. On all of these platforms, using -l to test individual outputs on the LED-WIZ will do random things when I type in a number to turn on an output. Most of the time, nothing happens. Sometimes, random LEDs would come on (even multiple LEDs at the same time). Other times, random LEDs that were on would turn off when I input a number.

Could these newer system (which all have newer, faster USB controllers) overwhelm the LED-WIZ? I noticed that RGBCommander has a setting that lets you throttle communications with the LED controller. I'm able to have RGBCommander turn on and off LEDs without any issues on these systems.

**Comment by myoung34** [comment]
USB3 is backwards compatible with USB2

What board are you using [from this list](https://sourceforge.net/p/ledspicer/wiki/Devices/)

**Comment by gray-space** [comment]
I'm using a Led-Wiz (32 LEDs). It's just on USB power, rather than hooking up an external supply. I'd be surprised if that's the cause, though. That would mean an old  netbook is able to supply enough current through its USB port for the Led-Wiz but not  the brand new desktop Mini-ATX motherboard board with a 500 Watt power supply. I don't have more LEDs hooked up to the board than the Led-Wiz instructions say it can handle when powered via USB (500Ma). 

I did find a reference in another open source interface project that [talks about  problems specifically with the Led-Wiz](http://pinball.weilenmann.net/docu/DirectOutputWIP/class_direct_output_1_1_cab_1_1_out_1_1_p_s_1_1_pinscape.html#af6e2dcec15b5d5a03f99ca1ddc8cb0dd). It apparently can  drop messages if they are sent at full USB speed. They added a configurable delay between sending messages to compensate. That matches what RGBCommander implies in its config example for the Led-Wiz. It has a higher suggested throttle setting than other controller boards.

**Comment by myoung34** [comment]
First thing I would try is to power it over the onboard power connector in addition to USB and see if that changes anything

**Comment by gray-space** [comment]
Hi. Rather than tearing apart the cabinet again to run wires, I decided to just install Windows and set up LedBlinky. That's working fine, so I'll be using that solution.

**Comment by meduzapat** [comment]
anyway I will checking the ledwiz code.
