### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by TheBlueKyanite** [meduzapat/LEDSpicer#5]
Hello, I followed the instructions located here: https://sourceforge.net/p/ledspicer/wiki/Deployment/#installing
to install LEDSpicer for my Ultimarc PAC Drive, but got stuck at the `sudo systemctl enable ledspicerd.service` part. 

It said that the `ledspicerd.service` file was not found, so I used the one from the examples folder (I also copied the example `ledspicer.conf` file). Now when I try starting the program, I get `Program terminated by error: Unable to read the file /usr/local/share/ledspicer/.xml Error=XML_ERROR_FILE_NOT_FOUND`

Any ideas on what I did wrong, and what I need to do to correct it?
Thanks

**Comment by meduzapat** [comment]
oh, sorry, I changed that, I will fix the documentation, I made it easier now, I will send you updated steps and change the documentation.

**Comment by meduzapat** [comment]
can you send me a message to the[ FB page](https://www.facebook.com/LEDSpicer-2393969390678210) so I can send you the details?

**Comment by TheBlueKyanite** [comment]
I currently don’t have a FB account.

**Comment by meduzapat** [comment]
I finished editing the install instruction, let me know if you have more questions, here.

**Comment by TheBlueKyanite** [comment]
Great, I’m able to install it now, and when I run `ledspicerd -v`, the version and info shows up. But now when I do `ledspicerd -d`, the same xml file not found error shows. Could this be due to the previously failed install?

**Comment by meduzapat** [comment]
you will need to configure it and create some profiles, I'm working right now on creating an automatic process to made things easier for new users, please [join this slack channel](https://join.slack.com/t/howlerskunkworks/shared_invite/zt-fzfbixqs-eCZN7fIzy3urZPCkChA~HQ) where other users can help you, you don't need to install slack, can be used from the browser.
