### ISSUE TITLE
Help setting up an ESP board.

### ISSUE THREAD

**Issue by dentex** [meduzapat/LEDSpicer#76]
Hello,
I'm trying to understand how to hook everything up and start doing some tests. 
I have an initial (no arcade controls, only a gamepad) and working raspberry pi 4 batocera setup, with the intent to put it into a DIY arcade cabinet later this year. I'm at the stage about understanding what arcade controls to use, so I've got to know about LEDSpicer.
I'll try to install/run it from Batocera later... For the moment I installed the .deb packages (main package and the adalight one) on my Linux Mint system.
Here I would like to understand how the adalight .deb works (I see it installed a .so file, I think it's a driver) and what to upload to an ESP board.

**EDIT: sorry for the noise: the Wiki clearly states "using WLED firmware"** ...

I think I'm still missing something about the full picture (and I might need a coffee...)

Thanks.

**Comment by meduzapat** [comment]
I can help you better here: discord.gg/m4D2QVXqm6
