### ISSUE TITLE
Suggested edit to install docs

### ISSUE THREAD

**Issue by mbdmbd** [meduzapat/LEDSpicer#81]
Thanks for your efforts on this project. Just wanted to mention that in the docs at https://github.com/meduzapat/LEDSpicer/wiki/Installing-LEDSpicer, it might be worth adding the need for libasound2-dev package in step - without it when attempting to configure (at least with the `--enable-mister` flag), it would fail when checking for alsa >= 0.2.

Solved for me when running `apt install libasound2-dev -y`

**Comment by meduzapat** [comment]
Good to know, if you don't want to use ALSA, you can also try, `--disable-alsaaudio`
